# Generated by Django 4.2.13 on 2024-06-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
