# Generated by Django 4.2.13 on 2024-07-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('allow_bidding', 'Allow Bidding on an Art')]},
        ),
    ]
