# Generated by Django 4.2.13 on 2024-07-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_customer_user_artwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('allow_add_artwork', 'Can add new Artwork')]},
        ),
    ]
