# Generated by Django 4.2.13 on 2024-07-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('allow_add_artwork', 'Can add new Artwork'), ('allow_change_artwork', 'Can change existed Artwork')]},
        ),
    ]
