# Generated by Django 4.2.13 on 2024-07-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_remove_customer_owned_artwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_artwork',
            new_name='user_artworks',
        ),
    ]
