# Generated by Django 4.2.13 on 2024-07-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_rename_user_artwork_customer_user_artworks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('allow_add_artwork', 'Can add new Artwork')]},
        ),
    ]
