# Generated by Django 4.2.13 on 2024-06-29 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='categories',
            field=models.ManyToManyField(to='Artworks.category'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='artwork',
            name='floor_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='selling_state',
            field=models.CharField(choices=[('not_sold', 'not_sold'), ('on_auction', 'on_auction'), ('pending', 'pending'), ('sold_out', 'sold_out')], default='not_sold', max_length=100),
        ),
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
