# Generated by Django 4.2.13 on 2024-06-30 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0003_alter_artwork_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hight', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('depth', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Artworks.artworksize'),
        ),
    ]
