# Generated by Django 4.2.13 on 2024-06-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0004_artworksize_alter_artwork_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
