# Generated by Django 4.2.13 on 2024-07-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0010_remove_artwork_owner_alter_artwork_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='categories',
        ),
    ]
