# Generated by Django 4.2.13 on 2024-07-05 11:46

import Artworks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0012_artwork_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['artist']},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/', validators=[Artworks.validators.validate_file_size]),
        ),
    ]
