# Generated by Django 4.2.13 on 2024-07-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0014_alter_artwork_floor_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtworkSize',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='size',
        ),
        migrations.AddField(
            model_name='artwork',
            name='depth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
