# Generated by Django 4.2.13 on 2024-07-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0015_delete_artworksize_remove_artwork_size_artwork_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.CharField(max_length=255),
        ),
    ]
